"$schema" = "schemas/schema.json"
plugin_name = "snap-layout"

[default]
description = "Default permissions for the snap-layout plugin"
permissions = ["allow-update-snap-bounds", "allow-detach-snap-bounds"]

[[permission]]
identifier = "allow-update-snap-bounds"
description = "Allows the frontend to update window snapping hitboxes"
commands.allow = ["update_snap_bounds"]

[[permission]]
identifier = "allow-detach-snap-bounds"
description = "Allows the frontend to detach window snapping hitboxes"
commands.allow = ["detach_snap_bounds"]